version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: TBK
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
